language: cpp
addons:
  homebrew:
    packages:
      - gfortran
matrix:
  include:
  - env: PLATFORM='linux64'
    os: linux
    dist: trusty
    sudo: required
    compiler: gcc
  - env: PLATFORM='windows32'
    os: linux
    dist: xenial 
    sudo: required
    compiler: gcc
  - env: PLATFORM='macos'
    os: osx
    osx_image: xcode8
    compiler: gcc
  - env: PLATFORM='musl64'
    os: linux
    dist: trusty
    sudo: required
    compiler: gcc
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then vm_stat; fi
  - df -h
  - ulimit -a
  - TARGET="${PLATFORM::${#PLATFORM}-2}"
  - "./build/${TARGET}/requirements.sh"
install:
  - source ./build/${TARGET}/build.sh
script:
  - echo "Nothing."
before_deploy:
  - mkdir -p dist
  - "./build/${TARGET}/package.sh"
deploy:
  provider: releases
  api_key:
    secure: ILnaYSSn9uaRUq8g0UOoAwdltVx9Qy/B7DPlt4ANMV3f4oxW9I7IotPnGcUpi7SzCAR9FlH9Drpct7awBWCXHRd9bp8nfhRnqnjwymhuyO08xkMYcdu3+TE5SjtKWnicakJZqwgAeUl0YSsEOl0M0A5LShKaFTn55tNQ/PPZe28=
  file:
    - "$(ls dist/*tar.gz dist/*.zip)"
  skip_cleanup: true
  on:
    repo: zhanxw/rvtests
    branch: master
    tags: true

